### ISSUE TITLE
Where is the ".i" file used with swig to create the wrapper ?

### ISSUE THREAD

**Issue by softlion** [BrunoMoureau/PocketSphinxXam#1]
I can't find it in the repo.

**Comment by BrunoMoureau** [comment]
Sorry, I can't remember how I built this. I suggest you to take a look at _https://cmusphinx.github.io/wiki/download/_
I certainly found it somewhere in there.

**Comment by BrunoMoureau** [comment]
I have added some information about how I built the android native libraries and C# wrapper classes. Take a look at https://github.com/BrunoMoureau/PocketSphinxXam/blob/master/README%20compilation.txt

I guess the '.i' files you are looking for are located at : 
 - https://github.com/cmusphinx/sphinxbase/tree/master/swig
 - https://github.com/cmusphinx/pocketsphinx/tree/master/swig

**Comment by softlion** [comment]
Np i managed to build them for both Android and iOS. But would have been faster and much easier to have the doc :)
Btw have you good result with the lib ? I'm a bit disappointed with some results.
Also you know how to recreate smaller or specialized data files ? Documents are not the best part of the project.

**Comment by BrunoMoureau** [comment]
Good job for both Android & iOS! Unfortunately, I am not used to gradle/swing tools so it took me a while to set up everything again. Sorry for the lack of docs and the delay...

Well, I think that PocketSphinx is still in a development phase so it would explain that some results are not always the expected ones. However, I managed to get closer to the results I wanted by setting the threshold value in the assets word files.

By smaller or specialized data files, do you mean that you want to set the speech recognition system on some words instead of the whole provided dictionary ?

**Comment by softlion** [comment]
Yes I remarked that when using phrase recognition using a small set of words in the rules (4/5 words per phrase), and having 5 different rules,  it tries absolutely to recognize these words and not the ones in the big dictionary. 

Btw I found a project on GitHub which rewrote the non engine part in c# and imports directly the main c interface. If my customer decides to continue with speech recognition I may switch to this implementation which seems to have more freedom in the recognition variables.

I want to thank you for your time. Without your project I won't think this would have been possible, and won't have tried at all. Note that I have a c/c++ background, and even if it's a bit far away now, I took pleasure to use the tools again. And it conforted me in my choice of C# a long time ago too ! Too much time spent in the toolings and boiler codes in C++ compared to c#.

**Comment by BrunoMoureau** [comment]
I'm glad to hear that my project helped you ! Thanks ! :)

If you base the speech recognition on list of words or sentences, it will only try to recognize these ones. 
I guess you can also make a free speech recognition based on the whole provided dictionary. I haven't tried this last one because I only needed specific words recognition for my project.

For instance, you can make a keyword file with this content :
my dog is pretty /1e-0/
my cat is pretty /1e-0/

It will only search these two sentences. The problem with this example is that the accuracy is so high that you will have to pronouce every words exactly how they are expected to be. 
Check the following link for further information about threshold and keywords detection. It seems also recommended to split up long sentences and increase the threshold value (to a maximum of 1e-50) to allow a better keywords detection : https://cmusphinx.github.io/wiki/tutoriallm/#keyword_lists
